on: [pull_request]
name: Clippy
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly
      - name: Formatting
        run: cargo +nightly fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: stable
      - name: Install linter
        run: cargo install cargo-lints
      - name: Lints
        run: cargo +stable lints clippy --all-targets --all-features
