name: Source Coverage
on:
  push:
    branches:
      - main
env:
  RUSTUP_TOOLCHAIN: "stable"
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq lcov
      - name: Download Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: {{ env.RUSTUP_TOOLCHAIN }}
          components: llvm-tools-preview
      - name: Install requirements for code coverage
        run: |
          cargo install cargo-binutils
          cargo install rustfilt
      - name: Run test coverage
        id: coverage
        env:
          SKIP_HTML: '1'
        run: |
          /bin/bash -c ./test_coverage.sh
      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./cov_raw/bulletproofs-plus.lcov
